services:
  zent-api-dev:
    container_name: zent-api-dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${API_PORT}:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - APP_ENV=development
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    profiles:
      - development
    restart: always


  zent-api-prod:
    container_name: zent-api-prod
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${API_PORT}:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - APP_ENV=production
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    profiles:
      - production
    restart: always
